# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - dbdata6:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  frontend:
    build:
      context: ./front-end
      target: dev
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./front-end/src/:/usr/src/app/src

  server:
    build:
      context: ./server
      target: dev
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017
    depends_on:
      - mongo
    volumes:
      - ./server/src:/usr/src/app/src
      - ./node_modules/:/usr/src/app/node_modules

volumes:
  dbdata6:
