# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    # ports:
    #   - 27017:27017
    expose: 
      - 27017
    volumes:
      - dbdata6:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  frontend:
    container_name: frontend
    build:
      context: ./front-end
      target: prod
      dockerfile: Dockerfile
    ports:
      - "80:80"

  server:
    container_name: server
    build:
      context: ./server
      target: prod
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://root:example@mongo:27017
    depends_on:
      - mongo

volumes:
  dbdata6:
