const obje = {
  id: '32173574',
  nodeId: 'MDQ6VXNlcjMyMTczNTc0',
  displayName: 'Kaddy Marindi',
  username: 'kaddy120',
  profileUrl: 'https://github.com/kaddy120',
  photos: [{ value: 'https://avatars.githubusercontent.com/u/32173574?v=4' }],
  provider: 'github',
  _raw: '{"login":"kaddy120","id":32173574,"node_id":"MDQ6VXNlcjMyMTczNTc0","avatar_url":"https://avatars.githubusercontent.com/u/32173574?v=4","gravatar_id":"","url":"ht tps://api.github.com/users/kaddy120","html_url":"https://github.com/kaddy120","followers_url":"https://api.github.com/users/kaddy120/followers","following_url":"https://a pi.github.com / users / kaddy120 / following{ /other_user}","gists_url":"https:/ / api.github.com / users / kaddy120 / gists{ /gist_id}","starred_url":"https:/ / api.github.com / users / kaddy 120 / starred{ /owner}{/repo } ","subscriptions_url":"https://api.github.com/users/kaddy120/subscriptions","organizations_url":"https://api.github.com/users/kaddy120/orgs","re pos_url":"https://api.github.com/users/kaddy120/repos","events_url":"https://api.github.com/users/kaddy120/events{/privacy}","received_events_url":"https://api.github.com /users/kaddy120 / received_events","type":"User","site_admin":false,"name":"Kaddy Marindi","company":null,"blog":"kaddy120.github.io","location":"South Africa","email":null , "hireable": null, "bio": null, "twitter_username": "KaddyDev", "public_repos": 16, "public_gists": 0, "followers": 0, "following": 2, "created_at": "2017-09-21T16:36:03Z", "updated_at": "2023-10-11T18:26:32Z"} ',
  _json: {
    login: 'kaddy120',
    id: 32173574,
    node_id: 'MDQ6VXNlcjMyMTczNTc0',
    avatar_url: 'https://avatars.githubusercontent.com/u/32173574?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/kaddy120',
    html_url: 'https://github.com/kaddy120',
    followers_url: 'https://api.github.com/users/kaddy120/followers',
    following_url:
      'https://api.github.com/users/kaddy120/following{/other_user}',
    gists_url: 'https://api.github.com/users/kaddy120/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/kaddy120/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/kaddy120/subscriptions',
    organizations_url: 'https://api.github.com/users/kaddy120/orgs',
    repos_url: 'https://api.github.com/users/kaddy120/repos',
    events_url: 'https://api.github.com/users/kaddy120/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/kaddy120/received_events',
    type: 'User',
    site_admin: false,
    name: 'Kaddy Marindi',
    company: null,
    blog: 'kaddy120.github.io',
    location: 'South Africa',
    email: null,
    hireable: null,
    bio: null,
    twitter_username: 'KaddyDev',
    public_repos: 16,
    public_gists: 0,
    followers: 0,
    following: 2,
    created_at: '2017-09-21T16:36:03Z',
    updated_at: '2023-10-11T18:26:32Z',
  },
};
