name: Deploy to Azure VM

on:
  push:
    branches:
      - main

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  VM_IP_ADDRESS: "52.146.92.120"
  APP_PATH: "/home/azureuser/myExpressApp"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setting up SSH
      run: |
        mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
        ssh-keyscan -H $VM_IP_ADDRESS >> ~/.ssh/known_hosts
        eval "$(ssh-agent -s)"
        ssh-add <(echo "$SSH_PRIVATE_KEY")
    - name: SSH into VM and Pull Code
      run: |
        ssh azureuser@$VM_IP_ADDRESS "cd $APP_PATH && git pull"

    - name: Start Application
      run: |
        ssh azureuser@$VM_IP_ADDRESS "cd $APP_PATH && npm install --production"
        ssh azureuser@$VM_IP_ADDRESS "cd $APP_PATH && npm start -w server"
        # scp -r ./* azureuser@$VM_IP_ADDRESS:$APP_PATH

